package org.yunzhong.NewsCollector.entity;

public class ArticleItemImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_item_image.id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_item_image.description
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_item_image.article_id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_item_image.item_id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_item_image.bytes
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    private byte[] bytes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_item_image.id
     *
     * @return the value of article_item_image.id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_item_image.id
     *
     * @param id the value for article_item_image.id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_item_image.description
     *
     * @return the value of article_item_image.description
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_item_image.description
     *
     * @param description the value for article_item_image.description
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_item_image.article_id
     *
     * @return the value of article_item_image.article_id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_item_image.article_id
     *
     * @param articleId the value for article_item_image.article_id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_item_image.item_id
     *
     * @return the value of article_item_image.item_id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_item_image.item_id
     *
     * @param itemId the value for article_item_image.item_id
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_item_image.bytes
     *
     * @return the value of article_item_image.bytes
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public byte[] getBytes() {
        return bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_item_image.bytes
     *
     * @param bytes the value for article_item_image.bytes
     *
     * @mbg.generated Tue Dec 12 09:50:06 GMT+08:00 2017
     */
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }
}