package org.yunzhong.NewsCollector.entity;

import java.util.Date;

public class Categories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.key
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.name
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.owner
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.create_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.update_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.key
     *
     * @return the value of categories.key
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.key
     *
     * @param key the value for categories.key
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.name
     *
     * @return the value of categories.name
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.name
     *
     * @param name the value for categories.name
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.owner
     *
     * @return the value of categories.owner
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.owner
     *
     * @param owner the value for categories.owner
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.create_time
     *
     * @return the value of categories.create_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.create_time
     *
     * @param createTime the value for categories.create_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.update_time
     *
     * @return the value of categories.update_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.update_time
     *
     * @param updateTime the value for categories.update_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}