package org.yunzhong.NewsCollector.entity;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.url
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.category
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.owner
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.publish_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.icon
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    private byte[] icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.url
     *
     * @return the value of news.url
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.url
     *
     * @param url the value for news.url
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.category
     *
     * @return the value of news.category
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.category
     *
     * @param category the value for news.category
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.owner
     *
     * @return the value of news.owner
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.owner
     *
     * @param owner the value for news.owner
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_time
     *
     * @return the value of news.create_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_time
     *
     * @param createTime the value for news.create_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.update_time
     *
     * @return the value of news.update_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.update_time
     *
     * @param updateTime the value for news.update_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.publish_time
     *
     * @return the value of news.publish_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.publish_time
     *
     * @param publishTime the value for news.publish_time
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.icon
     *
     * @return the value of news.icon
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public byte[] getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.icon
     *
     * @param icon the value for news.icon
     *
     * @mbg.generated Tue Dec 12 16:45:15 GMT+08:00 2017
     */
    public void setIcon(byte[] icon) {
        this.icon = icon;
    }
}